regionToStateMapping = {
 'tuscaloosa': 'AL',
 'twin tiers NY/PA': 'NY',
 'milwaukee': 'WI',
 'mansfield': 'OH',
 'lehigh valley': 'NJ',
 'gulfport / biloxi': 'MS',
 'peoria': 'IL',
 'western slope': 'CO',
 'frederick': 'MD',
 'roanoke': 'NC',
 'amarillo': 'TX',
 'panama city': 'FL',
 'hudson valley': 'NY',
 'dothan': 'AL',
 'eastern panhandle': 'FL',   
 'lima / findlay': 'OH',
 'jacksonville': 'FL',
 'knoxville': 'TN',
 'stillwater': 'OK',
 'jersey shore': 'NJ',
 'del rio / eagle pass': 'TX',
 'east oregon': 'OR',
 'fredericksburg': 'TX',
 'fayetteville': 'NC',
 'scranton / wilkes-barre': 'PA',
 'stockton': 'CA',
 'provo / orem': 'UT',
 'sacramento': 'CA',
 'state college': 'TX',
 'wyoming': 'WY',
 'auburn': 'AL',
 'wenatchee': 'WA',
 'binghamton': 'AL',
 'north central FL': 'FL',
 'champaign urbana': 'IL',
 'eastern NC': 'NC',
 'louisville': 'KY',
 'chico': 'CA',
 'yuba-sutter': 'CA',
 'orange county': 'CA',
 'little rock': 'AK',
 'lake charles': 'LA',
 'siskiyou county': 'CA',
 'lawrence': 'KS',
 'rochester': 'NY',
 'duluth / superior': 'MN',
 'st louis': 'MO',
 'brainerd': 'MN',
 'heartland florida': 'FL',
 'dayton / springfield': 'OH',
 'hartford': 'CT',
 'austin': 'TX',
 'san antonio': 'TX',
 'merced': 'CA',
 'bakersfield': 'IL',
 'oneonta': 'NY',
 'eastern CO': 'CO',
 'lake of the ozarks': 'MS',
 'tulsa': 'AZ',
 'fresno / madera': 'CA',
 'bend': 'OR',
 'deep east texas': 'TX',
 'corpus christi': 'TX',
 'hattiesburg': 'MS',
 'houston': 'TX',
 'inland empire': 'CA',
 'western massachusetts': 'MA',
 'eastern kentucky': 'KY',
 'the thumb': 'MI',
 'ft myers / SW florida': 'FL',
 'southern maryland': 'MD',
 'ithaca': 'NY',
 'college station': 'TX',
 'cape cod / islands': 'MA',
 'chattanooga': 'TN',
 'eastern montana': 'MT',
 'lubbock': 'TX',
 'hanford-corcoran': 'CA',
 'madison': 'WI',
 'killeen / temple / ft hood': 'TX',
 'joplin': 'MI',
 'las vegas': 'NV',
 'humboldt county': 'CA',
 'treasure coast': 'FL',
 'brunswick': 'NJ',
 'fort wayne': 'IN',
 'green bay': 'WI',
 'northern michigan': 'MI',
 'eastern shore': 'FL',
 'st cloud': 'MN',
 'cookeville': 'TN',
 'evansville': 'IL',
 'prescott': 'AZ',
 'la crosse': 'WI',
 'southwest michigan': 'MI',
 'winston-salem': 'NC',
 'north mississippi': 'MS',
 'glens falls': 'NY',
 'east idaho': 'ID',
 'erie': 'PA',
 'farmington': 'PA',
 'meadville': 'PA',
 'plattsburgh-adirondacks': 'NY',
 'manhattan': 'NY',
 'st joseph': 'MI',
 'baltimore': 'MD',
 'chautauqua': 'NY',
 'oregon coast': 'OR',
 'st louis, MO': 'MO',
 'rhode island': 'RI',
 'baton rouge': 'LA',
 'parkersburg-marietta': 'WV',
 'central NJ': 'NJ',
 'reading': 'PA',
 'flint': 'MI',
 'atlanta': 'GA',
 'imperial county': 'CA',
 'san angelo': 'TX',
 'salina': 'CA',
 'billings': 'MT',
 'mattoon-charleston': 'VA',
 'indianapolis': 'IN',
 'yakima': 'WA',
 'southwest MN': 'MN',
 'valdosta': 'GA',
 'muncie / anderson': 'IN',
 'zanesville / cambridge': 'MA',
 'charleston': 'VA',
 'redding': 'CA',
 'omaha / council bluffs': 'NE',
 'brownsville': 'TX',
 'mendocino county': '',
 'nashville': 'TN',
 'danville': 'CA',
 'st george': 'FL',
 'medford-ashland': 'OR',
 'waco': 'TX',
 'southeast alaska': 'AK',
 'wilmington': 'NC',
 'kansas city, MO': 'KS',
 'asheville': 'NC',
 'mcallen / edinburg': 'TX',
 'palm springs': 'FL',
 'utica-rome-oneida': 'KS',
 'gold country': 'CA',
 'york': 'PA',
 'grand island': 'MI',
 'portland': 'OR',
 'florida keys': 'FL',
 'fort collins / north CO': 'CO',
 'kennewick-pasco-richland': 'WA',
 'potsdam-canton-massena': 'NY',
 'tyler / east TX': 'TX',
 'cedar rapids': 'IA',
 'washington, DC': 'DC',
 'southeast KS': 'KS',
 'kenosha-racine': 'WI',
 'seattle-tacoma': 'WA',
 'santa fe / taos': 'NM',
 'butte': 'MT',
 'decatur': 'GA',
 'tucson': 'AZ',
 'augusta': 'GA',
 'dallas / fort worth': 'TX',
 'high rockies': 'CO',
 'sioux city': 'ND',
 'klamath falls': 'OR',
 'fairbanks': 'AK',
 'colorado springs': 'CA',
 'new orleans': 'LA',
 'waterloo / cedar falls': 'IA',
 'youngstown': 'OH',
 'richmond': 'VA',
 'upper peninsula': 'MI',
 'south jersey': 'NJ',
 'southwest TX': 'TX',
 'pueblo': 'AZ',
 'lincoln': 'NE',
 'elko': 'NV',
 'bloomington-normal': 'IN',
 'scottsbluff / panhandle': 'FL',
 'raleigh / durham / CH': 'NC',
 'greenville / upstate': 'SC',
 'bemidji': 'MN',
 'vermont': 'VT',
 'oklahoma city': 'OK',
 'mason city': 'IA',
 'holland': 'MI',
 'lafayette / west lafayette': 'IN',
 'fargo / moorhead': 'ND',
 'new hampshire': 'NH',
 'southwest MS': 'MS',
 'texoma': 'OK',
 'florence / muscle shoals': 'AL',
 'port huron': 'MI',
 'dubuque': 'IA',
 'western IL': 'IL',
 'iowa city': 'IA',
 'ventura county': 'CA',
 'muskegon': 'MI',
 'winchester': 'CA',
 "spokane / coeur d'alene": 'WA',
 'toledo': 'OH',
 'kalispell': 'MT',
 'clarksville': 'TN',
 'saginaw-midland-baycity': 'MI',
 'northwest OK': 'OK',
 'cleveland': 'OH',
 'sierra vista': 'AZ',
 'janesville': 'WI',
 'finger lakes': 'NY',
 'missoula': 'MT',
 'northwest GA': 'GA',
 'south bend / michiana': 'IN',
 'southwest KS': 'KS',
 'sandusky': 'OH',
 'space coast': 'FL',
 'northern WI': 'WI',
 'altoona-johnstown': 'OH',
 'santa barbara': 'CA',
 'boston': 'MA',
 'pittsburgh': 'PA',
 'kenai peninsula': 'AK',
 'pullman / moscow': 'WA',
 'helena': 'MT',
 'SF bay area': 'CA',
 'eugene': 'OR',
 'north platte': 'NE',
 'new haven': 'CT',
 'south florida': 'FL',
 'hickory / lenoir': 'NC',
 'greensboro': 'NC',
 'quad cities, IA/IL': 'IA',
 'ashtabula': 'OH',
 'williamsport': 'PA',
 'catskills': 'NY',
 'salem': 'OR',
 'memphis': 'TN',
 'show low': 'AZ',
 'kansas city': 'MO',
 'myrtle beach': 'SC',
 'athens': 'GA',
 'eau claire': 'WI',
 'modesto': 'CA',
 'tampa bay area': 'FL',
 'new york city': 'NY',
 'philadelphia': 'PA',
 'santa maria': 'CA',
 'hawaii': 'HI',
 'lexington': 'KY',
 'macon / warner robins': 'GA',
 'albuquerque': 'NM',
 'meridian': 'IA',
 'jackson': 'MI',
 'lansing': 'MI',
 'fort dodge': 'IA',
 'pierre / central SD': 'SD',
 'shreveport': 'LA',
 'eastern CT': 'CT',
 'long island': 'NY',
 'clovis / portales': 'NM',
 'delaware': 'DE',
 'southern WV': 'WV',
 'south dakota': 'SD',
 'logan': 'UT',
 'fort smith, AR': 'AR',
 'st augustine': 'FL',
 'mohave county': 'AZ',
 'anchorage / mat-su': 'AK',
 'okaloosa / walton': 'FL',
 'outer banks': 'NC',
 'el paso': 'TX',
 'ogden-clearfield': 'UT',
 'lewiston / clarkston': 'ID',
 'abilene': 'TX',
 'sarasota-bradenton': 'FL',
 'annapolis': 'MD',
 'central michigan': 'MI',
 'bowling green': '',
 'bellingham': 'WA',
 'monroe': 'MI',
 'owensboro': 'KY',
 'akron / canton': 'OH',
 'galveston': 'TX',
 'topeka': 'KS',
 'maine': 'ME',
 'texarkana': 'TX',
 'florence': 'SC',
 'columbia / jeff city': 'MO',
 'fort smith': 'AK',
 'kokomo': 'IN',
 'northeast SD': 'SD',
 'jonesboro': 'AR',
 'northwest KS': 'KS',
 'worcester / central MA': 'MA',
 'orlando': 'FL',
 'columbia': 'SC',
 'northern panhandle': 'FL',
 'elmira-corning': 'NY',
 'western maryland': 'MD',
 'bozeman': 'MT',
 'daytona beach': 'FL',
 'olympic peninsula': 'WA',
 'huntington-ashland': 'OH',
 'watertown': 'NY',
 'beaumont / port arthur': 'TX',
 'tallahassee': '',
 'sheboygan': 'WI',
 'skagit / island / SJI': 'AK',
 'southern illinois': 'IL',
 'bismarck': 'ND',
 'wichita': 'KS',
 'lancaster': 'PA',
 'rapid city / west SD': 'SD',
 'north jersey': 'NJ',
 'bloomington': 'IN',
 'houma': 'LA',
 'ann arbor': 'MI',
 'tuscarawas co': 'OH',
 'charlottesville': 'VA',
 'kirksville': 'MO',
 'battle creek': 'MI',
 'central louisiana': 'LA',
 'wichita falls': 'KS',
 'sioux falls / SE SD': 'SD',
 'mobile': 'AL',
 'las cruces': 'NM',
 'odessa / midland': 'TX',
 'new river valley': 'VA',
 'ames': 'IA',
 'gainesville': 'FL',
 'montgomery': 'AL',
 'flagstaff / sedona': 'AZ',
 'great falls': 'MT',
 'victoria': 'TX',
 'norfolk / hampton roads': 'VA',
 'pensacola': 'FL',
 'harrisburg': 'PA',
 'boise': 'ID',
 'laredo': 'TX',
 'west virginia (old)': 'WV',
 'hilton head': 'SC',
 'roswell / carlsbad': 'CA',
 'visalia-tulare': 'CA',
 'birmingham': 'AL',
 'boone': 'NC',
 'southeast missouri': 'MS',
 'western KY': 'KY',
 'lynchburg': 'VA',
 'morgantown': 'WV',
 'boulder': 'CO',
 'twin falls': 'WA',
 'moses lake': '',
 'lakeland': 'FL',
 'southeast IA': 'IA',
 'harrisonburg': 'VA',
 'san marcos': 'TX',
 'rockford': 'IL',
 'yuma': 'AZ',
 'tri-cities': 'WA',
 'lafayette': 'MS',
 'denver': 'CO',
 'reno / tahoe': 'CA',
 'chicago': 'IL',
 'cincinnati': 'OH',
 'charlotte': 'NC',
 'corvallis/albany': 'NY',
 'grand rapids': 'MI',
 'mankato': 'MN',
 'wausau': 'WI',
 'syracuse': 'NY',
 'columbus': 'OH',
 'south coast': 'MA',
 'lawton': 'OK',
 'minneapolis / st paul': 'MN',
 'la salle co': 'CO',
 'kalamazoo': 'MI',
 'los angeles': 'CA',
 'roseburg': 'OR',
 'terre haute': 'IN',
 'san diego': 'CA',
 'susanville': 'CA',
 'statesboro': 'GA',
 'southwest VA': 'VA',
 'albany': 'NY',
 'grand forks': 'ND',
 'monterey bay': 'CA',
 'ocala': 'FL',
 'cumberland valley': 'PA',
 'buffalo': 'NY',
 'north dakota': 'ND',
 'des moines': 'IA',
 'appleton-oshkosh-FDL': 'WI',
 'springfield': 'MO',
 'gadsden-anniston': 'AL',
 'san luis obispo': 'CA',
 'salt lake city': 'UT',
 'huntsville / decatur': 'AL',
 'northwest CT': 'CT',
 'savannah / hinesville': 'GA',
 'phoenix': 'AZ',
 'poconos': 'PA',
 'chillicothe': 'OH',
 'detroit metro': 'MI'
}
